name: All Contributors

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  allcontributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: all-contributors/all-contributors-cli@<commit-sha>
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
